# Model parameters
IMG_SIZE = 448
GRID_SIZE = 7
BOXES_PER_CELL = 2
NUM_CLASSES = 20

# Training parameters
LEARNING_RATE = 1e-2
EPOCHS = 135
BATCH_SIZE = 64
MOMENTUM = 0.9
WEIGHT_DECAY = 5e-4
LAMBDA_COORD = 5
LAMBDA_NOOBJ = 0.5